### PR TITLE
Added Markdown support in speaker, event, member details

### PR DESCRIPTION
**Pull request by xprilion**
It is now possible to add markdown content in speaker, event and team details.

The `marked` library as a mixin and `v-html` bindings were used.

### CODE REVIEW

**Comment by bharatagsrwal** [comment]
Thank you @xprilion, we appreciate your effort in making Aura application a great, but v-html makes Aura application Cross-site scripting (XSS) vulnerable and markdown converts text to HTML and this can leads to security issues in the admin panel.

**Comment by xprilion** [comment]
Hi @bharatagsrwal, do you think a filter would be a better way to do this? Sorry, I'm new to Vue and am unaware of the small nuances 😓

I'll update the PR as per suggestions!

**Comment by bharatagsrwal** [comment]
XSS is not a small vulnerability, it can harm the complete application.
https://vuejs.org/v2/guide/security.html#Injecting-HTML

**Comment by xprilion** [comment]
@bharatagsrwal Yes, I'm aware of XSS. 

 Do you think a filter would be a better way to do this?

**Comment by xprilion** [comment]
Further, since the data is being fetched from the backend, and we know it has been entered manually via the Aura Admin, what are the chances of the data being unsafe?

**Pull request closed without merging**
